version: '3.2'
services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      COMPOSER_HOME: /var/cache/composer
    volumes:
      - './app:/var/www/html:delegated'
      - './data/composer:/var/cache/composer'
  nginx:
    depends_on:
      - fpm
    image: nginx:1.15.8-alpine
    ports:
      - '${NGINX_PORT:-8080}:80'
    volumes:
      - './app/public:/var/www/html/public:delegated'
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
